import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


const Home = ({data}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="descrip" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ height: 300, backgroundColor: 'yellow', display: 'flex'}}>
<p>heeeeeeeeeeeoooooooooooooooo</p>
{ data.results.map( (item, index) => {
  console.log("🚀 ~ file: index.tsx ~ line 21 ~ Home ~ item", item)
  return (
    <div key={index} style={{ backgroundColor: 'green', border: '5px dashed black'}}>
      <p>{item.title}</p>
      <p>{item.category}</p>
      <p>{item.category}</p>
    </div>
  )
})}

      </main>
    </div>
  )
}

export async function getServerSideProps() {

  const res = await fetch(`https://api.predicthq.com/v1/events?limit=30`, {
    headers: {
      Authorization: `Bearer ${process.env.ACCESS_TOKEN}`, 
      Accept: 'application/json', 
      'Content-Type': 'application/json'
    }
  }); 
  const data = await res.json();
  return { props: { data } }
  
}

export default Home
